# Paste content of your `netlify.toml` file here
[[plugins]]
package = "@netlify/plugin-nextjs, @sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "allspreads"
    sentryProject = "javascript-nextjs"
