# Paste content of your `netlify.toml` file here
[[plugins]]
package = "@netlify/plugin-nextjs"
[[plugins]]
package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "allspreads"
    sentryProject = "javascript-nextjs"
    sentryRepository = "github.com/GPFAFF/allspreads"
