export const data = [
  {
    month: "September",
    picks: [
      {
        date: "09/05/22",
        team: "Chicago White Sox",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/06/22",
        team: "Chicago Cubs Cincinnati Reds Under 8",
        odds: "-115",
        result: "loser",
      },
      {
        date: "09/06/22",
        team: "Chicago White Sox / Seattle Mariners Over 7.5",
        odds: "-117",
        result: "loser",
      },
      {
        date: "09/07/22",
        team: "Philadelphia Phillies RL F5 -0.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/058/22",
        team: "Gabe Davis - Anytime TD",
        odds: "+140",
        result: "winner",
      },
      {
        date: "09/08/22",
        team: "Gabe Davis - Over 62.5 Yards",
        odds: "-120",
        result: "winner",
      },
      {
        date: "09/08/22",
        team: "Josh Allen - Over 23.5 Completions",
        odds: "-120",
        result: "winner",
      },
      {
        date: "09/08/22",
        team: "Cam Akers - Over 13.5 Receiving",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/08/22",
        team: "Buffalo Bills / Los Angeles Rams Over 52",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/09/22",
        team: "Louisville / UCF Under 61.5",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/10/22",
        team: "Alabama -20",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/10/22",
        team: "USC -8.5",
        odds: "-115",
        result: "winner",
      },
      {
        date: "09/10/22",
        team: "Tennessee -6.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/11/22",
        team: "Baltimore 1H Under 22",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/11/22",
        team: "Nick Chubb Anytime TD",
        odds: "+100",
        result: "loser",
      },
      {
        date: "09/11/22",
        team: "Trey Lance Over 38.5 Rushing yards",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/11/22",
        team: "Chargers vs Raiders Over 52",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/11/22",
        team: "Julio Jones Over 38.5 Receiving yards",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/12/22",
        team: "Rashad Penny - Under 69.5 rushing yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/12/22",
        team: "Jerry Jeudy - Over 60.5 Receiving yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/12/22",
        team: "Denver Broncos -6.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/13/22",
        team: "Los Angeles Angels",
        odds: "+117",
        result: "loser",
      },
      {
        date: "09/14/22",
        team: "Baltimore Orioles -1.5 RL",
        odds: "+134",
        result: "winner",
      },
      {
        date: "09/14/22",
        team: "Seattle Mariners -1.5 RL",
        odds: "+152",
        result: "winner",
      },
      {
        date: "09/14/22",
        team: "Tampa Bay Rays ML",
        odds: "-102",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Minnesota Twins -1.5 RL",
        odds: "+120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Philadelphia Phillies ML",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Los Angeles Chargers 1H +3",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/15/22",
        team: "Chiefs v Chargers Under 54",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/15/22",
        team: "Travis Kelce - Over 6.5 Receptions",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Travis Kelce - Over 78.5 receiving yards",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Austin Ekeler - Over 37.5 receiving yards",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/05/22",
        team: "Chicago White Sox",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/15/22",
        team: "Mike Williams - Over 69.5 receiving yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/16/22",
        team: "Air Force - 15",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/16/22",
        team: "Air Force / Wyoming - Over 46",
        odds: "-105",
        result: "loser",
      },
      {
        date: "09/16/22",
        team: "Florida State -2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/16/22",
        team: "Wyoming 2H +8",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/17/22",
        team: "Notre Dame -10.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "App St / Troy - Under 52.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Miami / Texas A&M - Under 46",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Maryland -2.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Michigan State +3.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Nebraska / Oklahoma - Over 65",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Eastern Michigan / Arizona State - 1H Over 29.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Arkansas St / Memphis - 1H Under 33.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Arkansas St / Memphis - 1H Under 33.5",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Georgia - 1H -14",
        odds: "-110",
        result: null,
      },
      {
        date: "09/17/22",
        team: "Indiana / Western Kentucky - Under 61",
        odds: "-110",
        result: null,
      },
    ],
  },
];
