export const data = [
  {
    month: "September",
    picks: [
      {
        date: "09/05/22",
        team: "Chicago White Sox",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/06/22",
        team: "Chicago Cubs Cincinnati Reds Under 8",
        odds: "-115",
        result: "loser",
      },
      {
        date: "09/06/22",
        team: "Chicago White Sox / Seattle Mariners Over 7.5",
        odds: "-117",
        result: "loser",
      },
      {
        date: "09/07/22",
        team: "Philadelphia Phillies RL F5 -0.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/058/22",
        team: "Gabe Davis - Anytime TD",
        odds: "+140",
        result: "winner",
      },
      {
        date: "09/08/22",
        team: "Gabe Davis - Over 62.5 Yards",
        odds: "-120",
        result: "winner",
      },
      {
        date: "09/08/22",
        team: "Josh Allen - Over 23.5 Completions",
        odds: "-120",
        result: "winner",
      },
      {
        date: "09/08/22",
        team: "Cam Akers - Over 13.5 Receiving",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/08/22",
        team: "Buffalo Bills / Los Angeles Rams Over 52",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/09/22",
        team: "Louisville / UCF Under 61.5",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/10/22",
        team: "Alabama -20",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/10/22",
        team: "USC -8.5",
        odds: "-115",
        result: "winner",
      },
      {
        date: "09/10/22",
        team: "Tennessee -6.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/11/22",
        team: "Baltimore 1H Under 22",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/11/22",
        team: "Nick Chubb Anytime TD",
        odds: "+100",
        result: "loser",
      },
      {
        date: "09/11/22",
        team: "Trey Lance Over 38.5 Rushing yards",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/11/22",
        team: "Chargers vs Raiders Over 52",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/11/22",
        team: "Julio Jones Over 38.5 Receiving yards",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/12/22",
        team: "Rashad Penny - Under 69.5 rushing yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/12/22",
        team: "Jerry Jeudy - Over 60.5 Receiving yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/12/22",
        team: "Denver Broncos -6.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/13/22",
        team: "Los Angeles Angels",
        odds: "+117",
        result: "loser",
      },
      {
        date: "09/14/22",
        team: "Baltimore Orioles -1.5 RL",
        odds: "+134",
        result: "winner",
      },
      {
        date: "09/14/22",
        team: "Seattle Mariners -1.5 RL",
        odds: "+152",
        result: "winner",
      },
      {
        date: "09/14/22",
        team: "Tampa Bay Rays ML",
        odds: "-102",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Minnesota Twins -1.5 RL",
        odds: "+120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Philadelphia Phillies ML",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Los Angeles Chargers 1H +3",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/15/22",
        team: "Chiefs v Chargers Under 54",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/15/22",
        team: "Travis Kelce - Over 6.5 Receptions",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Travis Kelce - Over 78.5 receiving yards",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/15/22",
        team: "Austin Ekeler - Over 37.5 receiving yards",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/05/22",
        team: "Chicago White Sox",
        odds: "-117",
        result: "winner",
      },
      {
        date: "09/15/22",
        team: "Mike Williams - Over 69.5 receiving yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/16/22",
        team: "Air Force - 15",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/16/22",
        team: "Air Force / Wyoming - Over 46",
        odds: "-105",
        result: "loser",
      },
      {
        date: "09/16/22",
        team: "Florida State -2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/16/22",
        team: "Wyoming 2H +8",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/17/22",
        team: "Notre Dame -10.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/17/22",
        team: "App St / Troy - Under 52.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/17/22",
        team: "Miami / Texas A&M - Under 46",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/17/22",
        team: "Maryland -2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/17/22",
        team: "Michigan State +3.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/17/22",
        team: "Nebraska / Oklahoma - Over 65",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/17/22",
        team: "Eastern Michigan / Arizona State - 1H Over 29.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/17/22",
        team: "Arkansas St / Memphis - 1H Under 33.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/17/22",
        team: "Georgia - 1H -14",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/17/22",
        team: "Indiana / Western Kentucky - Under 61",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/18/22",
        team: "Seattle / SF - 1H Under 21",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/18/22",
        team: "Carolina Panthers TT - Over 20.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/18/22",
        team: "Jaguars +3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/18/22",
        team: "Panthers +2",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/18/22",
        team: "Los Angeles Rams / Atlanta Falcons - Over 46.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/18/22",
        team: "Nick Chubb - Over 83.5 yards rushing",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/18/22",
        team: "Joe Mixon - Over 70.5 yards rushing",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/18/22",
        team: "Derek Carr - Over 282.5 yards passing",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/18/22",
        team: "Tampa Bay vs. Saints - Under 43.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/18/22",
        team: "Cleveland vs New York - Under 39.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/18/22",
        team: "Aaron Jones - Anytime TD",
        odds: "+100",
        result: "winner",
      },
      {
        date: "09/19/22",
        team: "Treylon Burks - Over 29.5 receiving yards",
        odds: "-115",
        result: "winner",
      },
      {
        date: "09/19/22",
        team: "Eagles 1H -0.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/19/22",
        team: "Eagles / Vikings 1H Under 24",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/20/22",
        team: "Baltimore Orioles RL -1.5",
        odds: "-105",
        result: "loser",
      },
      {
        date: "09/20/22",
        team: "Houston Astros ML",
        odds: "+122",
        result: "winner",
      },
      {
        date: "09/20/22",
        team: "Atlanta Braves RL -1.5",
        odds: "-155",
        result: "loser",
      },
      {
        date: "09/20/22",
        team: "Blue Jays / Phillies - Over 8.5",
        odds: "-113",
        result: "winner",
      },
      {
        date: "09/19/22",
        team: "Marlins / Cubs - Under 7",
        odds: "-113",
        result: "winner",
      },
      {
        date: "09/20/22",
        team: "Mike Clevinger - Over 3.5 K's",
        odds: "+108",
        result: null,
      },
      {
        date: "09/20/22",
        team: "Dylan Cease - Over 6 K's",
        odds: "-135",
        result: "loser",
      },
      {
        date: "09/21/22",
        team: "Orioles vs. Tiger - Under 8",
        odds: "100",
        result: "loser",
      },
      {
        date: "09/21/22",
        team: "Reds vs Red Sox - Under 10.5",
        odds: "-105",
        result: "winner",
      },
      {
        date: "09/21/22",
        team: "Yankees -1.5 RL",
        odds: "-135",
        result: "winner",
      },
      {
        date: "09/21/22",
        team: "Phillies vs. Blue Jays - Over 8.5",
        odds: "-105",
        result: "loser",
      },
      {
        date: "09/21/22",
        team: "Dodgers vs. Diamondbacks - Over 9",
        odds: "+105",
        result: "loser",
      },
      {
        date: "09/22/22",
        team: "Mariners ML",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/22/22",
        team: "Padres ML",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/22/22",
        team: "Orioles vs Astros - Over 7",
        odds: "-110",
        result: "loser",
      },

      {
        date: "09/22/22",
        team: "Browns vs. Steelers - Under 40.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/22/22",
        team: "West Virginia vs Virginia Tech - Under 51.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/22/22",
        team: "Nick Chubb - Over 16.5 carries",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/22/22",
        team: "Mitch Trubisky - Over 0.5 INT's",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/22/22",
        team: "Kareem Hunt - Over 16.5 receving yards",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/22/22",
        team: "Najee Harris - Over 14.5 carries",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/22/22",
        team: "Amari Cooper - Over 48.5 receiving yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/22/22",
        team: "Dodgers vs Diamondbacks - Over 7",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/23/22",
        team: "Red Sox TT - Over 2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/23/22",
        team: "Air Force -24",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/23/22",
        team: "Boise State -3.5 1Q",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "UL Lafayette vs UL Monroe - Over 51",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "Sacramento State -1",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/24/22",
        team: "USC -5.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "Georgia vs Kent State - Under 62",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/24/22",
        team: "Arkansas ML",
        odds: "+110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "Indiana vs. Cincinnati - Over 52.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/24/22",
        team: "Texas vs. Texas Tech - Under 62",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "Western Michigan vs. San Jose State - Over 49",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "Kansas -7",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/24/22",
        team: "Buffalo vs. Eastern Michigan - Under 59",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/24/22",
        team: "Maryland -17",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/24/22",
        team: "Wyoming TT Under 13.5",
        odds: "+120",
        result: "loser",
      },
      {
        date: "09/25/22",
        team: "Bills vs. Dolphins - Under 54",
        odds: "+120",
        result: "winner",
      },
      {
        date: "09/25/22",
        team: "Chiefs vs. Colts - Under 51",
        odds: "+120",
        result: "winner",
      },
      {
        date: "09/25/22",
        team: "Amon-Ra St. Brown - Over 6.5 receptions",
        odds: "-120",
        result: "loser",
      },
      {
        date: "09/25/22",
        team: "Michael Carter - Over 9.5 carries",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/25/22",
        team: "Bengals TT Over 25.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/25/22",
        team: "Titans vs. Raiders - Over 45.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/25/22",
        team: "Titans vs. Raiders - 1H Under 23.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/25/22",
        team: "Falcons TT O 20.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/25/22",
        team: "49ers v Broncos - Under 44.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/26/22",
        team: "Cowboys +1",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/26/22",
        team: "Daniel Jones - Under 205 passing yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/26/22",
        team: "Noah Brown - Over 45.5 receiving yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/27/22",
        team: "Tampa Bay Rays ML",
        odds: "+134",
        result: "winner",
      },
      {
        date: "09/27/22",
        team: "Mike Yastrzemski - Over 0.5 hits",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/27/22",
        team: "Corbin Carroll - Over 0.5 hits",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/27/22",
        team: "Michael Massey - Over 0.5 hits",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/27/22",
        team: "Michael Taylor - Over 0.5 hits",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/27/22",
        team: "Ian Happ - Over 0.5 hits",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/28/22",
        team: "Reds vs. Pirates - Over 7.5",
        odds: "-118",
        result: "loser",
      },
      {
        date: "09/28/22",
        team: "Paolo Espino - Over 4.0 strikeouts",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/28/22",
        team: "Mariners ML",
        odds: "-154",
        result: "winner",
      },
      {
        date: "09/28/22",
        team: "Houston ML",
        odds: "-172",
        result: "loser",
      },
      {
        date: "09/28/22",
        team: "Tristian McKenzie - Under 6.5 K's",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/29/22",
        team: "Dolphins TT - Over 21.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/29/22",
        team: "Joe Burrow - Over 11.5 rushing yards",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/29/22",
        team: "Joe Mixon - Under 70.5 rushing yards",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/29/22",
        team: "Jaylen Waddle - Over 67.5 receiving yards",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/29/22",
        team: "Cleveland Guardians vs. Tampa Bay Rays - Under 6.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/29/22",
        team: "Chicago Cubs vs. Philadelphia Phillies - Under 7.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/29/22",
        team: "Cincinnati Bengals -3.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/29/22",
        team: "Utah State TT - Under 17.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "09/30/22",
        team: "Boise State vs. San Diego State - Over 38",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/30/22",
        team: "UCLA +3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/30/22",
        team: "UTSA -4",
        odds: "-110",
        result: "winner",
      },
      {
        date: "09/30/22",
        team: "Houston vs Tulane - Under 54.5",
        odds: "-110",
        result: "winner",
      },
    ],
  },
  {
    month: "October",
    picks: [
      {
        date: "10/01/22",
        team: "Mississippi St 1H -2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "Michigan -9.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "Minnesota -9",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "Pittsburgh -20",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "Ole Miss -6",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "Wyoming vs. San Jose State - Over 42",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "Fresno State vs. UConn - Under 52.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "Coastal Carolina vs. Georgia Southern - Over 58",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "Oregon State vs Utah - Over 54.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "South Alabama vs. ULL - Over 47.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "Troy vs. Western Kentucky - Over 54.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/01/22",
        team: "Texas State +22",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "Purdue vs. Minnesota - 1H Over 27",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "USC -25",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/01/22",
        team: "Oregon -17",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Saints +3.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Saints vs. Vikings Under 42",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/02/22",
        team: "Cardinals +2",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Giants -3.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Browns vs. Falcons - Over 47.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/02/22",
        team: "Tennessee Titans +3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Las Vegas Raiders -2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Washington Commanders +3.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/02/22",
        team: "New England Patriots +10.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/02/22",
        team: "Eagles vs. Jaguars - Under 44",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/03/22",
        team: "Brandon Aiyuk - Over 52.5 receiving yards",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/03/22",
        team: "Milwaukee Brewers ML",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/03/22",
        team: "Deebo Samuel - Over 28.5 rushing yards",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/03/22",
        team: "Matthew Stafford - Over passing 34.5 attempts",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/03/22",
        team: "SF 49ers 2H ML",
        odds: "+135",
        result: "winner",
      },
      {
        date: "10/04/22",
        team: "Texas Rangers ML",
        odds: "+115",
        result: "loser",
      },
      {
        date: "10/04/22",
        team: "Diamondback F5 -0.5",
        odds: "+117",
        result: "loser",
      },
      {
        date: "10/05/22",
        team: "UCF -3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/05/22",
        team: "Alec Pierce - Over 42.5 yards receiving",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/05/22",
        team: "Jerry Jeudy - Over 48.5 yards receiving",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/05/22",
        team: "Cortland Sutton - Over 64.5 yards receiving",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/05/22",
        team: "Colts vs. Broncos - Over 41.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/05/22",
        team: "Mets vs. Padres - Under 6.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/08/22",
        team: "Guardians ML -120",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "Guardians vs. Rays - Under 6.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "Phillies vs. Cardinals - Over 7",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "St. Louis Cardinals",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/08/22",
        team: "Shane Bieber - Over 5.5 K's",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "Luis Castillo - Over 14.5 recorded outs",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "Rutgers +3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "Houston ML",
        odds: "+125",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "San Jose State -6.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/08/22",
        team: "Colorado State +4",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Florida vs. Missouri - Under 54",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Mississippi St 2H +1.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Tennessee -3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Tennessee vs. LSU - Over 62",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/09/22",
        team: "Mississippi State vs. Arkansas - Under 57",
        odds: "-110",
        result: "push",
      },
      {
        date: "10/09/22",
        team: "Louisville -3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Alabama -24",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/09/22",
        team: "Oregon vs. Arizona - Under 70.5",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/09/22",
        team: "Kent State vs. Miami Ohio - Under 57.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Georgia Southern -2.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "Georgia Southern vs. Georgia State - Over 65",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "UCLA +5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/09/22",
        team: "UCONN -5.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/10/22",
        team: "Browns vs. Chargers - Over 47.5",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/10/22",
        team: "Eagles 1H -3",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/10/22",
        team: "Nick Chubb - Over 17.5 carries",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/10/22",
        team: "Detroit Lions ML",
        odds: "+150",
        result: "loser",
      },
      {
        date: "10/10/22",
        team: "Ravens 1H -2",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/10/22",
        team: "Lamar Jackson - Over 9.5 carries",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/10/22",
        team: "Saints vs. Seahawks - Over 45",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/11/22",
        team: "Raiders vs. Chiefs - Over 51",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/11/22",
        team: "David Carr - Under 39.5 passing attempts",
        odds: "-110",
        result: "winner",
      },
      {
        date: "10/11/22",
        team: "Travis Kelce - Over 76.5 receiving yards",
        odds: "-110",
        result: "loser",
      },
      {
        date: "10/12/22",
        team: "Braves vs. Phillies - Over 7",
        odds: "-110",
        result: null,
      },
      {
        date: "10/12/22",
        team: "Gerrit Cole - Under 6.5 Strikeouts",
        odds: "-130",
        result: null,
      },
      {
        date: "10/12/22",
        team: "Dodgers vs. Padres - Over 7",
        odds: "-130",
        result: null,
      },
      {
        date: "10/12/22",
        team: "Braves -1.5 RL",
        odds: "+105",
        result: null,
      },
    ],
  },
];
